apiVersion: apps/v1
kind: Deployment

metadata:
  name: my-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: my-app

  template:
    metadata:
      labels:
        app: my-app

    spec:
      containers:
      - name: my-container
        image: lakshmana0303/devops-prod-app:latest
        
        env:
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: APP_NAME

        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: PASSWORD
